// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc0-AxDdIh0b6B2CrKj6bQqg-txz7XpXI',
    appId: '1:991660504042:web:0dbf6edd7d411f144b3893',
    messagingSenderId: '991660504042',
    projectId: 'timeleft-f60fd',
    authDomain: 'timeleft-f60fd.firebaseapp.com',
    storageBucket: 'timeleft-f60fd.firebasestorage.app',
    measurementId: 'G-G7WK2JMXF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQjQEsI9MlE6ZQbkyp08VrmzjuYu9oZ8s',
    appId: '1:991660504042:android:abc38969748157034b3893',
    messagingSenderId: '991660504042',
    projectId: 'timeleft-f60fd',
    storageBucket: 'timeleft-f60fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5bT0jCjFqSswQom-4kEMnQH7ud-zl-EM',
    appId: '1:991660504042:ios:c6a16b0f9b5622634b3893',
    messagingSenderId: '991660504042',
    projectId: 'timeleft-f60fd',
    storageBucket: 'timeleft-f60fd.firebasestorage.app',
    iosClientId:
        '991660504042-3a834ic9vo7ppuddk2a7thd5s28g4ltu.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeleftClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5bT0jCjFqSswQom-4kEMnQH7ud-zl-EM',
    appId: '1:991660504042:ios:c6a16b0f9b5622634b3893',
    messagingSenderId: '991660504042',
    projectId: 'timeleft-f60fd',
    storageBucket: 'timeleft-f60fd.firebasestorage.app',
    iosClientId:
        '991660504042-3a834ic9vo7ppuddk2a7thd5s28g4ltu.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeleftClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc0-AxDdIh0b6B2CrKj6bQqg-txz7XpXI',
    appId: '1:991660504042:web:e7dec03acdcf6d714b3893',
    messagingSenderId: '991660504042',
    projectId: 'timeleft-f60fd',
    authDomain: 'timeleft-f60fd.firebaseapp.com',
    storageBucket: 'timeleft-f60fd.firebasestorage.app',
    measurementId: 'G-ZMW711K5ZZ',
  );
}
