"""Added connection logic for notifications

Revision ID: 324bdd6f2d40
Revises: ddd6e5cd36ef
Create Date: 2025-09-07 20:06:16.354998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '324bdd6f2d40'
down_revision: Union[str, Sequence[str], None] = 'ddd6e5cd36ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chats', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chats', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('messages', 'message_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('messages', 'sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('messages', 'sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'message_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('chats', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('chats', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chats', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
