"""add cascade delete to bookings.user_id

Revision ID: 369396b8cd1a
Revises: 4a8a4033e4be
Create Date: 2025-09-04 21:51:05.784882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '369396b8cd1a'
down_revision: Union[str, Sequence[str], None] = '4a8a4033e4be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
