"""add rating fields to bookings

Revision ID: 4a8a4033e4be
Revises: d370a1e7738a
Create Date: 2025-09-04 19:31:33.428895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a8a4033e4be'
down_revision: Union[str, Sequence[str], None] = 'd370a1e7738a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('has_been_rated', sa.Boolean(), nullable=False))
    op.add_column('bookings', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'rating')
    op.drop_column('bookings', 'has_been_rated')
    # ### end Alembic commands ###
