"""add cascade delete to bookings.user_id

Revision ID: 8a409673ce3b
Revises: 369396b8cd1a
Create Date: 2025-09-04 22:01:29.867506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a409673ce3b'
down_revision: Union[str, Sequence[str], None] = '369396b8cd1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bookings_user_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('bookings_dinner_id_fkey'), 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'dinners', ['dinner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'bookings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
    op.drop_constraint(op.f('notifications_booking_id_fkey'), 'notifications', type_='foreignkey')
    op.drop_constraint(op.f('notifications_dinner_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notifications', 'dinners', ['dinner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_dinner_id_fkey'), 'notifications', 'dinners', ['dinner_id'], ['id'])
    op.create_foreign_key(op.f('notifications_booking_id_fkey'), 'notifications', 'bookings', ['booking_id'], ['id'])
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('bookings_dinner_id_fkey'), 'bookings', 'dinners', ['dinner_id'], ['id'])
    op.create_foreign_key(op.f('bookings_user_id_fkey'), 'bookings', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
