"""your new changes

Revision ID: bc1d8bdd890a
Revises: b3896400703b
Create Date: 2025-09-01 18:41:48.503485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc1d8bdd890a'
down_revision: Union[str, Sequence[str], None] = 'b3896400703b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country', sa.String(), nullable=True))
    op.add_column('users', sa.Column('dinner_languages', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('dinner_budget', sa.String(), nullable=True))
    op.add_column('users', sa.Column('has_dietary_restrictions', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('dietary_options', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('event_push_notifications', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('event_sms', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('event_email', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('lastminute_push_notifications', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('lastminute_sms', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('lastminute_email', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('marketing_email', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('is_subscribed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('subscription_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('subscription_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('subscription_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('subscription_plan_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
