"""add notifications and scheduled notifications tables

Revision ID: d370a1e7738a
Revises: 0a310e65ffda
Create Date: 2025-09-03 22:42:48.966325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd370a1e7738a'
down_revision: Union[str, Sequence[str], None] = '0a310e65ffda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
