"""Add cascade delete constraints to foreign keys

Revision ID: ec73addda79a
Revises: 67b2c88befa7
Create Date: 2025-09-10 17:49:54.986225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec73addda79a'
down_revision: Union[str, Sequence[str], None] = '67b2c88befa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chats_user1_id_fkey'), 'chats', type_='foreignkey')
    op.drop_constraint(op.f('chats_user2_id_fkey'), 'chats', type_='foreignkey')
    op.drop_constraint(op.f('chats_dinner_id_fkey'), 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'dinners', ['dinner_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'chats', 'users', ['user1_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chats', 'users', ['user2_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('messages_chat_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_sender_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_sender_id_fkey'), 'messages', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(op.f('messages_chat_id_fkey'), 'messages', 'chats', ['chat_id'], ['id'])
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.create_foreign_key(op.f('chats_dinner_id_fkey'), 'chats', 'dinners', ['dinner_id'], ['id'])
    op.create_foreign_key(op.f('chats_user2_id_fkey'), 'chats', 'users', ['user2_id'], ['id'])
    op.create_foreign_key(op.f('chats_user1_id_fkey'), 'chats', 'users', ['user1_id'], ['id'])
    # ### end Alembic commands ###
